apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-cfg
  labels:
    app: yulibaozi-webhook
webhooks:
  - name: sidecar.yulibaozi.com
    clientConfig:
      service:
        name: yulibaozi-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0ekNDQVVTZ0F3SUJBZ0lKQUphUVcvdHRobEx6TUFvR0NDcUdTTTQ5QkFNQ01CZ3hGakFVQmdOVkJBTU0KRFd0MVltVnlibVYwWlhNdFkyRXdIaGNOTVRrd01UQTNNRE0wTlRReVdoY05Namt3TVRBME1ETTBOVFF5V2pBWQpNUll3RkFZRFZRUUREQTFyZFdKbGNtNWxkR1Z6TFdOaE1JR2JNQkFHQnlxR1NNNDlBZ0VHQlN1QkJBQWpBNEdHCkFBUUJQbElyZ05ITVNGQnJhS09sb3FKdENiQXRIQURmV3lZQ0w2SzN4b1c1ZjRYSm1rTzhvaXJYZWM5NGVDMCsKSjN3aGFsd1ZxNTltVlJvOUFRdzR3ZW1VVWljQXFyTThJVDZ1b0s3aEdvUW1hSTFBQjcrcTdzQklMZVhBWGNUTwp1b2owRVFpWnFZVUlrN2xJUm43MFZORUdpUzE4M1lqejZtN2R0aGdCb0F2RkxjMVU0R2FqTkRBeU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRVFRSU1BYUhCQXFYb0VZd0NnWUkKS29aSXpqMEVBd0lEZ1l3QU1JR0lBa0lBb25RZ3BDS1pMWlVWSVQ3bU5FQzZsb3dlNDNCcGEwS3VmMFFTU1UrUgpSbC9YUGdNQUZpRklBREZSMkorZnpSa0Y0Mng2a1k2ZWo4ZDkzYVhFdVduUVU1QUNRZ0htSWoyU2ZvV0x6QUUyCmVYM2o0WkE3ejg1Tk9leE5leC9KeUJtWDRSdER1QVEzTEt0cDlmSFhYc1p1Y2tUbTdSemhxTXNvMWh5MWRwcjMKT2luY2FDZjBRQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    # namespaceSelector:
    #   matchLabels:
    #     yulibaozi-webhook: enabled

