apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecaruser
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: sidecaruser
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sidecaruser
subjects:
- kind: ServiceAccount
  name: sidecaruser
  namespace: default
 # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sidecaruser
  apiGroup: rbac.authorization.k8s.io