apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: confs.first.yulibaozi.com
spec:
  group: first.yulibaozi.com
  version: v1beta1
  scope: Namespaced
  names:
    plural: confs
    singular: conf
    kind: MyConf
    shortNames:
    - mc
---
apiVersion: "first.yulibaozi.com/v1beta1"
kind: MyConf
metadata:
  name: sidecarconf
data:
  sidecar: "{\"name\":\"sidecar-nginx\",\"image\":\"nginx:1.12.2\",\"resources\":{},\"imagePullPolicy\":\"IfNotPresent\"}"